### ISSUE TITLE
Paper proof does not have references

### ISSUE THREAD

**Issue by Benjamin-Lee** [AliYoussef96/BCAW-Tool#2]
[The most recent proof](https://github.com/openjournals/joss-papers/blob/joss.01500/joss.01500/10.21105.joss.01500.pdf) does not have references rendered at the bottom. I'm not sure of the cause of the error (maybe @arfon or @mgymrek can help out), but we'll need to fix it before we publish the paper.

**Comment by arfon** [comment]
Thanks for flagging this @Benjamin-Lee.

@AliYoussef96 - This is because you're not actually citing the references in your bibtex file correctly so Pandoc doesn't know what to include in your reference list. You can read how to cite them [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by AliYoussef96** [comment]
I think there are now references in the paper. I edited what is wrong with [paper.md](https://github.com/AliYoussef96/BCAW-Tool/blob/master/paper/paper.md)

**Comment by arfon** [comment]
I think this is now fixed in https://github.com/openjournals/joss-papers/blob/joss.01500/joss.01500/10.21105.joss.01500.pdf
